services:
  hublink-gateway:
    image: neurotechhub/hublink-gateway:latest
    restart: always
    privileged: true
    network_mode: host
    stop_grace_period: 30s
    stop_signal: SIGTERM
    entrypoint: ["/usr/local/bin/docker-entrypoint.sh"]
    command: ["python3", "/app/main.py"]
    volumes:
      - ${LOCAL_STORAGE_PATH}/data:/data:z
      - /dev:/dev:ro
      - /run/udev:/run/udev:ro
      - /media:/media:rshared
      - /var/run/dbus:/var/run/dbus
      - /var/run/bluetooth:/var/run/bluetooth
      - ./docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh:ro
    environment:
      - LOCAL_STORAGE_PATH=${LOCAL_STORAGE_PATH}
      - REMOVEABLE_STORAGE_PATH=${REMOVEABLE_STORAGE_PATH}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/status"]
      interval: 30s

  watchtower:
    image: containrrr/watchtower:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=300