services:
  hublink-gateway:
    image: neurotechhub/hublink-gateway:latest
    restart: always
    privileged: true
    network_mode: host
    stop_grace_period: 30s
    stop_signal: SIGTERM
    volumes:
      - ${LOCAL_STORAGE_PATH}:${LOCAL_STORAGE_PATH}
      - /media/${USER}/HUBLINK:/media:rw
      - /dev:/dev:ro
      - /run/udev:/run/udev:ro
      - /media:/media:rshared
      - /var/run/dbus:/var/run/dbus
      - /var/run/bluetooth:/var/run/bluetooth
    environment:
      - LOCAL_STORAGE_PATH=${LOCAL_STORAGE_PATH}
      - MEDIA_STORAGE_PATH=/media
      - ENVIRONMENT=prod
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/status"]
      interval: 30s

  watchtower:
    image: containrrr/watchtower:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=3600